export const filterButtons = [
  { id: 1, label: "All" },
  { id: 2, label: "Music" },
  { id: 3, label: "Live" },
  { id: 4, label: "Gaming" },
  { id: 5, label: "News" },
  { id: 6, label: "Sports" },
  { id: 7, label: "Podcasts" },
  { id: 8, label: "Movies" },
  { id: 9, label: "Trending" },
  { id: 10, label: "Learning" },
  { id: 11, label: "Comedy" },
  { id: 12, label: "Technology" },
  { id: 13, label: "Fashion" },
  { id: 14, label: "Travel" },
  { id: 15, label: "Food" },
  { id: 16, label: "Science" },
  { id: 17, label: "Fitness" },
  { id: 18, label: "Motivation" },
  { id: 19, label: "Cars" },
  { id: 20, label: "Nature" },
  { id: 21, label: "Documentary" },
  { id: 22, label: "Animation" },
  { id: 23, label: "DIY" },
  { id: 24, label: "History" },
  { id: 25, label: "Education" },
];

export const videos = [
  {
    videoId: "1",
    title: "Amazing Nature Documentary - Wildlife in 4K",
    thumbnailUrl: "https://picsum.photos/800/450?random=1",
    uploader: "Nature Explorer",
    views: 1234567,
    uploadDate: "2024-03-15",
    likes: 45000,
    dislikes: 1200,
    description:
      "Experience the breathtaking beauty of wildlife in stunning 4K resolution. This documentary takes you on a journey through some of the world's most spectacular natural habitats.",
    duration: "12:45",
  },
  {
    videoId: "2",
    title: "Modern Web Development Tutorial",
    thumbnailUrl: "https://picsum.photos/800/450?random=2",
    uploader: "Code Master",
    views: 892345,
    uploadDate: "2024-03-10",
    likes: 32000,
    dislikes: 800,
    description: "Learn modern web development techniques and best practices.",
    duration: "25:30",
  },
  {
    videoId: "3",
    title: "Cooking the Perfect Pasta",
    thumbnailUrl: "https://picsum.photos/800/450?random=3",
    uploader: "Chef's Kitchen",
    views: 567890,
    uploadDate: "2024-03-08",
    likes: 28000,
    dislikes: 500,
    description: "Master the art of cooking perfect pasta every time.",
    duration: "8:20",
  },
  {
    videoId: "4",
    title: "Travel Vlog: Tokyo Adventures",
    thumbnailUrl: "https://picsum.photos/800/450?random=4",
    uploader: "World Traveler",
    views: 445672,
    uploadDate: "2024-03-05",
    likes: 22000,
    dislikes: 300,
    description:
      "Join me on an incredible journey through Tokyo's hidden gems.",
    duration: "15:12",
  },
  {
    videoId: "5",
    title: "Amazing Nature Documentary - Wildlife in 4K",
    thumbnailUrl: "https://picsum.photos/800/450?random=1",
    uploader: "Nature Explorer",
    views: 1234567,
    uploadDate: "2024-03-15",
    likes: 45000,
    dislikes: 1200,
    description:
      "Experience the breathtaking beauty of wildlife in stunning 4K resolution. This documentary takes you on a journey through some of the world's most spectacular natural habitats.",
    duration: "12:45",
  },
  {
    videoId: "6",
    title: "Modern Web Development Tutorial",
    thumbnailUrl: "https://picsum.photos/800/450?random=2",
    uploader: "Code Master",
    views: 892345,
    uploadDate: "2024-03-10",
    likes: 32000,
    dislikes: 800,
    description: "Learn modern web development techniques and best practices.",
    duration: "25:30",
  },
  {
    videoId: "7",
    title: "Cooking the Perfect Pasta",
    thumbnailUrl: "https://picsum.photos/800/450?random=3",
    uploader: "Chef's Kitchen",
    views: 567890,
    uploadDate: "2024-03-08",
    likes: 28000,
    dislikes: 500,
    description: "Master the art of cooking perfect pasta every time.",
    duration: "8:20",
  },
  {
    videoId: "8",
    title: "Travel Vlog: Tokyo Adventures",
    thumbnailUrl: "https://picsum.photos/800/450?random=4",
    uploader: "World Traveler",
    views: 445672,
    uploadDate: "2024-03-05",
    likes: 22000,
    dislikes: 300,
    description:
      "Join me on an incredible journey through Tokyo's hidden gems.",
    duration: "15:12",
  },
  {
    videoId: "9",
    title: "Amazing Nature Documentary - Wildlife in 4K",
    thumbnailUrl: "https://picsum.photos/800/450?random=1",
    uploader: "Nature Explorer",
    views: 1234567,
    uploadDate: "2024-03-15",
    likes: 45000,
    dislikes: 1200,
    description:
      "Experience the breathtaking beauty of wildlife in stunning 4K resolution. This documentary takes you on a journey through some of the world's most spectacular natural habitats.",
    duration: "12:45",
  },
  {
    videoId: "10",
    title: "Modern Web Development Tutorial",
    thumbnailUrl: "https://picsum.photos/800/450?random=2",
    uploader: "Code Master",
    views: 892345,
    uploadDate: "2024-03-10",
    likes: 32000,
    dislikes: 800,
    description: "Learn modern web development techniques and best practices.",
    duration: "25:30",
  },
  {
    videoId: "11",
    title: "Cooking the Perfect Pasta",
    thumbnailUrl: "https://picsum.photos/800/450?random=3",
    uploader: "Chef's Kitchen",
    views: 567890,
    uploadDate: "2024-03-08",
    likes: 28000,
    dislikes: 500,
    description: "Master the art of cooking perfect pasta every time.",
    duration: "8:20",
  },
  {
    videoId: "12",
    title: "Travel Vlog: Tokyo Adventures",
    thumbnailUrl: "https://picsum.photos/800/450?random=4",
    uploader: "World Traveler",
    views: 445672,
    uploadDate: "2024-03-05",
    likes: 22000,
    dislikes: 300,
    description:
      "Join me on an incredible journey through Tokyo's hidden gems.",
    duration: "15:12",
  },
  {
    videoId: "13",
    title: "Amazing Nature Documentary - Wildlife in 4K",
    thumbnailUrl: "https://picsum.photos/800/450?random=1",
    uploader: "Nature Explorer",
    views: 1234567,
    uploadDate: "2024-03-15",
    likes: 45000,
    dislikes: 1200,
    description:
      "Experience the breathtaking beauty of wildlife in stunning 4K resolution. This documentary takes you on a journey through some of the world's most spectacular natural habitats.",
    duration: "12:45",
  },
  {
    videoId: "14",
    title: "Modern Web Development Tutorial",
    thumbnailUrl: "https://picsum.photos/800/450?random=2",
    uploader: "Code Master",
    views: 892345,
    uploadDate: "2024-03-10",
    likes: 32000,
    dislikes: 800,
    description: "Learn modern web development techniques and best practices.",
    duration: "25:30",
  },
  {
    videoId: "15",
    title: "Cooking the Perfect Pasta",
    thumbnailUrl: "https://picsum.photos/800/450?random=3",
    uploader: "Chef's Kitchen",
    views: 567890,
    uploadDate: "2024-03-08",
    likes: 28000,
    dislikes: 500,
    description: "Master the art of cooking perfect pasta every time.",
    duration: "8:20",
  },
  {
    videoId: "16",
    title: "Travel Vlog: Tokyo Adventures",
    thumbnailUrl: "https://picsum.photos/800/450?random=4",
    uploader: "World Traveler",
    views: 445672,
    uploadDate: "2024-03-05",
    likes: 22000,
    dislikes: 300,
    description:
      "Join me on an incredible journey through Tokyo's hidden gems.",
    duration: "15:12",
  },
];

 export  const defaultVideo = {
    title: "Default Video Title",
    description: "This is a default description in case the API fails or returns no data.",
    thumbnailUrl: "https://via.placeholder.com/400x300",
    videoID: "j6HGO9OMTvY",
    category: "Live",
  };
