export const filterButtons = [
  { id: 1, label: "All" },
  { id: 2, label: "Music" },
  { id: 3, label: "Live" },
  { id: 4, label: "Gaming" },
  { id: 5, label: "News" },
  { id: 6, label: "Sports" },
  { id: 7, label: "Podcasts" },
  { id: 8, label: "Movies" },
  { id: 9, label: "Trending" },
  { id: 10, label: "Learning" },
  { id: 11, label: "Comedy" },
  { id: 12, label: "Technology" },
  { id: 13, label: "Fashion" },
  { id: 14, label: "Travel" },
  { id: 15, label: "Food" },
  { id: 16, label: "Science" },
  { id: 17, label: "Fitness" },
  { id: 18, label: "Motivation" },
  { id: 19, label: "Cars" },
  { id: 20, label: "Nature" },
  { id: 21, label: "Documentary" },
  { id: 22, label: "Animation" },
  { id: 23, label: "DIY" },
  { id: 24, label: "History" },
  { id: 25, label: "Education" },
];
